[tools]
typos = "latest"
gitleaks = "latest"
python = "3.13"
uv = "latest"
node = "26"
"pipx:commitizen" = "latest"
yamllint = "latest"
actionlint = "latest"
stylua = "latest"
"github:huacnlee/autocorrect" = "latest"
tombi = "latest"
prettier = "latest"
markdownlint-cli2 = "latest"
prek = "latest"

[tools."github:editorconfig-checker/editorconfig-checker"]
version = "3"
matching = "editorconfig-checker"

[tools."github:luarocks/luarocks"]
version = "3.12"
os = ["windows"]

[tools."http:lua"]
version = "5.1.5"
os = ["windows"]
# https://github.com/ScoopInstaller/Versions/blob/master/bucket/lua51.json
platforms.windows-x64.url = "https://downloads.sourceforge.net/project/luabinaries/5.1.5/Tools%20Executables/lua-5.1.5_Win64_bin.zip"
